# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    card:
      quality: 75
      filters:
        thumbnail: { size: [360, 230], mode: outbound }
    view:
      quality: 75
      filters:
        thumbnail: { size: [530, 360], mode: outbound }
    thumb:
      quality: 75
      filters:
        thumbnail: { size: [120, 90], mode: outbound }
    carousel:
      quality: 75
      filters:
        thumbnail: { size: [400, 150], mode: outbound }
